[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[server]
maxUploadSize = 25

[theme]
base = "light"
primaryColor = "#7657FF"
backgroundColor = "#F5F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172033"
font = "sans serif"
